Repository YAPP-Github/20th-ALL-Rounder-Team-1-iOS, pull requests merged in 2022-08, with the labels that each got.

#160 CategoryEdit, ScheduleEdit 내 오류 개선
  Weekand/Weekand/Presentation/MainScene/Category/Coordinator/CategoryCoordinator.swift
  Weekand/Weekand/Presentation/MainScene/Category/View/CategoryEditViewController.swift
  Weekand/Weekand/Presentation/MainScene/Category/View/ColorSheetViewController.swift
  Weekand/Weekand/Presentation/MainScene/ScheduleEdit/ViewModel/CategoryListSheetViewModel.swift
Labels: :bug: 버그, :lipstick: UI

#161 팔로우의 일정 완료, 미완료 처리 할수없도록 개선
  Weekand/Weekand/Presentation/MainScene/Main/Coordinator/MainCoordinator.swift
  Weekand/Weekand/Presentation/MainScene/Main/ViewModel/MainViewModel.swift
Labels: :bug: 버그, :lipstick: UI

#159 스티커가 없어도 1개 보이는 이슈 해결, 일정리스트 API 변경 대응
  Weekand/Weekand.xcodeproj/project.pbxproj
  Weekand/Weekand/API.swift
  Weekand/Weekand/Domain/Entities/ScheduleMain.swift
  Weekand/Weekand/Domain/UseCase/Main/MainUseCase.swift
  Weekand/Weekand/Networking/Query/scheduleList.graphql
  Weekand/Weekand/Presentation/MainScene/Common/View/WEmojiView.swift
  Weekand/Weekand/Presentation/MainScene/Main/View/MainViewController.swift
  Weekand/Weekand/Presentation/MainScene/Main/View/SubView/MainView/MainTableViewCell.swift
  Weekand/Weekand/Presentation/MainScene/Main/ViewModel/MainViewModel.swift
  Weekand/Weekand/schema.json
Labels: :bug: 버그, 🖥 Networking

#162 일정 스킵, 이후 모든일정 삭제 기능 적용
  Weekand/Weekand/Presentation/MainScene/Main/View/MainViewController.swift
  Weekand/Weekand/Presentation/MainScene/Main/View/SubView/MainView/MainTableViewCell.swift
Labels: 🖥 Networking

#163 스티커 조회/추가 오류 수정, 스티커추가 후 일정리스트 새로고침
  Weekand/Weekand/Presentation/MainScene/Main/Coordinator/MainCoordinator.swift
  Weekand/Weekand/Presentation/MainScene/Main/View/MainViewController.swift
  Weekand/Weekand/Presentation/MainScene/Main/ViewModel/Sheet/StickerAddSheetViewModel.swift
Labels: :bug: 버그

#167 ScheduleDetail, Sign Scene UI 개선
  Weekand/Weekand.xcodeproj/project.pbxproj
  Weekand/Weekand/Domain/CompleteStatus.swift
  Weekand/Weekand/Presentation/MainScene/ScheduleDetail/View/Views/CompleteCollectionViewCell.swift
  Weekand/Weekand/Presentation/MainScene/ScheduleDetail/View/Views/ScheduleCompleteToolBar.swift
  Weekand/Weekand/Presentation/SignScene/SignUp/Coordinator/SignUpCoordinator.swift
  Weekand/Weekand/Presentation/SignScene/SignUp/View/SignUpAddInfomationViewController.swift
  Weekand/Weekand/Presentation/SignScene/SignUp/View/SignUpTermsViewController.swift
  Weekand/Weekand/Resources/Assets.xcassets/Symbols/EmptyViewEmoji/searchEmoji.empty.imageset/Contents.json
  Weekand/Weekand/Resources/Assets.xcassets/Symbols/EmptyViewEmoji/searchEmoji.empty.imageset/searchEmoji.empty.png
  Weekand/Weekand/Resources/Assets.xcassets/Symbols/EmptyViewEmoji/searchEmoji.empty.imageset/searchEmoji.empty2x.png
  Weekand/Weekand/Resources/Assets.xcassets/Symbols/EmptyViewEmoji/searchEmoji.empty.imageset/searchEmoji.empty3x.png
  Weekand/Weekand/Resources/Assets.xcassets/Symbols/EmptyViewEmoji/searchEmoji.empty.imageset/userEmoji.empty.png
  Weekand/Weekand/Resources/Assets.xcassets/Symbols/EmptyViewEmoji/searchEmoji.empty.imageset/userEmoji.empty2x.png
  Weekand/Weekand/Resources/Assets.xcassets/Symbols/EmptyViewEmoji/searchEmoji.empty.imageset/userEmoji.empty3x.png
Labels: :lipstick: UI

#168 알람 화면, 팔로워/팔로잉 목록 화면, 메인화면 팔로잉 목록 Pagination
  Weekand/Weekand/Domain/Alarm.swift
  Weekand/Weekand/Domain/ProfileUseCase.swift
  Weekand/Weekand/Domain/UseCase/Main/MainUseCase.swift
  Weekand/Weekand/Presentation/MainScene/Main/View/AlarmViewController.swift
  Weekand/Weekand/Presentation/MainScene/Main/View/MainViewController.swift
  Weekand/Weekand/Presentation/MainScene/Main/View/SubView/AlarmTableViewCell.swift
  Weekand/Weekand/Presentation/MainScene/Main/ViewModel/AlarmViewModel.swift
  Weekand/Weekand/Presentation/MainScene/Main/ViewModel/MainViewModel.swift
  Weekand/Weekand/Presentation/ProfileScene/Profile/View/FollowViewController.swift
  Weekand/Weekand/Presentation/ProfileScene/Profile/ViewModel/FollowViewModel.swift
Labels: 🖥 Networking

#169 이미지 캐싱 처리 및 메인 일정 리스트 스와이프 적용
  Weekand/Weekand.xcodeproj/project.pbxproj
  Weekand/Weekand/Presentation/MainScene/Main/View/MainScheduleDataSource.swift
  Weekand/Weekand/Presentation/MainScene/Main/View/MainViewController.swift
  Weekand/Weekand/Presentation/MainScene/Main/View/Sheet/StickerAddSheet.swift
  Weekand/Weekand/Presentation/MainScene/Main/View/SubView/MainView/MainCollectionViewCell.swift
  Weekand/Weekand/Presentation/MainScene/Main/View/SubView/MainView/MainProfileView.swift
  Weekand/Weekand/Presentation/MainScene/Main/View/SubView/Sheet/EmojiTableViewCell.swift
  Weekand/Weekand/Presentation/MainScene/Main/ViewModel/MainViewModel.swift
  Weekand/Weekand/Presentation/MainScene/Main/ViewModel/Sheet/EmojiTableViewModel.swift
  Weekand/Weekand/Presentation/MainScene/Search/View/SubView/UserTableViewCell.swift
  Weekand/Weekand/Presentation/ProfileScene/Profile/View/ProfileEditViewController.swift
  Weekand/Weekand/Presentation/ProfileScene/Profile/View/ProfileViewController.swift
  Weekand/Weekand/Presentation/Utils/Manager/ImageCacheManager.swift
Labels: :bug: 버그, :lipstick: UI

#172 팔로워, 팔로잉 리스트 이미지 캐싱처리 및 일정 추가 시 시간값 보정 기능 추가
  Weekand/Weekand/Presentation/MainScene/ScheduleEdit/View/ScheduleEditViewController.swift
  Weekand/Weekand/Presentation/ProfileScene/Profile/View/SubView/FollowTableViewCell.swift
Labels: :lipstick: UI

#174 AppLifeCycle 관련 오류 및 UI 개선사항 적용
  Weekand/Weekand/Application/SceneDelegate.swift
  Weekand/Weekand/Presentation/MainScene/Category/View/CategoryEditViewController.swift
  Weekand/Weekand/Presentation/Utils/Extensions/UIVIewController+modality.swift
Labels: :bug: 버그, :lipstick: UI

#179 스티커 추가시 기존 스티커 확인 기능, 월간 달력 이슈 해결
  Weekand/Weekand.xcodeproj/project.pbxproj
  Weekand/Weekand/API.swift
  Weekand/Weekand/Domain/UseCase/Main/MainUseCase.swift
  Weekand/Weekand/Networking/Query/MyStickerAdded.graphql
  Weekand/Weekand/Presentation/MainScene/Main/View/Sheet/MonthlyCalendarSheet.swift
  Weekand/Weekand/Presentation/MainScene/Main/View/Sheet/StickerAddSheet.swift
  Weekand/Weekand/Presentation/MainScene/Main/ViewModel/Sheet/StickerAddSheetViewModel.swift
Labels: :bug: 버그, :lipstick: UI

#181 다른 화면에서 돌아오면 팔로잉 목록에 Selection 테두라가 사라지는 문제 #180
  Weekand/Weekand/Presentation/MainScene/Main/View/MainViewController.swift
  Weekand/Weekand/Presentation/MainScene/Main/ViewModel/MainViewModel.swift
Labels: :bug: 버그, :lipstick: UI
